# Using lightweight alpine image
FROM python:3.8-alpine

# Installing packages
RUN apk update
RUN pip install --no-cache-dir pipenv

# Defining working directory and adding source code
WORKDIR /usr/src/STT_API_REST
COPY Pipfile Pipfile.lock bootstrap.sh ./
COPY STT ./STT

# Install API dependencies
RUN pipenv install --system --deploy

# Start app
EXPOSE 5000
ENTRYPOINT ["/usr/src/STT_API_REST/bootstrap.sh"]